
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/jem/.antigravity/antigravity/bin/"
      - "/Users/jem/.opencode/bin/"
      - "/Users/jem/.bun/bin/"
      - "/Users/jem/.yarn/bin/"
      - "/Users/jem/.config/yarn/global/node_modules/.bin/"
      - "/Users/jem/.local/state/fnm_multishells/29375_1771963794114/bin/"
      - "/Users/jem/go/bin/"
      - "/Users/jem/code/repos/pixlet/"
      - "/Users/jem/.n/bin/"
      - "/Users/jem/.radicle/bin/"
      - "/Users/jem/.local/bin/"
      - "/Users/jem/Library/pnpm/"
      - "/Users/jem/.local/state/fnm_multishells/22271_1771961984275/bin/"
      - "/Users/jem/.zi/polaris/sbin/"
      - "/Users/jem/.zi/polaris/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/go/bin/"
      - "/Applications/Postgres.app/Contents/Versions/latest/bin/"
      - "/Users/jem/.cargo/bin/"
      - "/Applications/Ghostty.app/Contents/MacOS/"
      - "/Users/jem/.foundry/bin/"
      - "/Users/jem/.cache/lm-studio/bin/"
    searched_directories:
      - "/Users/jem/.antigravity/antigravity/bin/uname"
      - "/Users/jem/.opencode/bin/uname"
      - "/Users/jem/.bun/bin/uname"
      - "/Users/jem/.yarn/bin/uname"
      - "/Users/jem/.config/yarn/global/node_modules/.bin/uname"
      - "/Users/jem/.local/state/fnm_multishells/29375_1771963794114/bin/uname"
      - "/Users/jem/go/bin/uname"
      - "/Users/jem/code/repos/pixlet/uname"
      - "/Users/jem/.n/bin/uname"
      - "/Users/jem/.radicle/bin/uname"
      - "/Users/jem/.local/bin/uname"
      - "/Users/jem/Library/pnpm/uname"
      - "/Users/jem/.local/state/fnm_multishells/22271_1771961984275/bin/uname"
      - "/Users/jem/.zi/polaris/sbin/uname"
      - "/Users/jem/.zi/polaris/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/jem/.antigravity/antigravity/bin"
        - "/Users/jem/.opencode/bin"
        - "/Users/jem/.bun/bin"
        - "/Users/jem/.yarn/bin"
        - "/Users/jem/.config/yarn/global/node_modules/.bin"
        - "/Users/jem/.local/state/fnm_multishells/29375_1771963794114/bin"
        - "/Users/jem/go/bin"
        - "/Users/jem/code/repos/pixlet"
        - "/Users/jem/.n/bin"
        - "/Users/jem/.radicle/bin"
        - "/Users/jem/.antigravity/antigravity/bin"
        - "/Users/jem/.opencode/bin"
        - "/Users/jem/.local/bin"
        - "/Users/jem/.bun/bin"
        - "/Users/jem/Library/pnpm"
        - "/Users/jem/.yarn/bin"
        - "/Users/jem/.config/yarn/global/node_modules/.bin"
        - "/Users/jem/.local/state/fnm_multishells/22271_1771961984275/bin"
        - "/Users/jem/.zi/polaris/sbin"
        - "/Users/jem/.zi/polaris/bin"
        - "/Users/jem/go/bin"
        - "/Users/jem/code/repos/pixlet"
        - "/Users/jem/.n/bin"
        - "/Users/jem/.radicle/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/go/bin"
        - "/Applications/Postgres.app/Contents/Versions/latest/bin"
        - "/Users/jem/.cargo/bin"
        - "/Applications/Ghostty.app/Contents/MacOS"
        - "/Users/jem/.foundry/bin"
        - "/Users/jem/.cache/lm-studio/bin"
        - "/Users/jem/.foundry/bin"
        - "/Users/jem/.cache/lm-studio/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 23.4.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/jem/.antigravity/antigravity/bin/"
      - "/Users/jem/.opencode/bin/"
      - "/Users/jem/.bun/bin/"
      - "/Users/jem/.yarn/bin/"
      - "/Users/jem/.config/yarn/global/node_modules/.bin/"
      - "/Users/jem/.local/state/fnm_multishells/29375_1771963794114/bin/"
      - "/Users/jem/go/bin/"
      - "/Users/jem/code/repos/pixlet/"
      - "/Users/jem/.n/bin/"
      - "/Users/jem/.radicle/bin/"
      - "/Users/jem/.local/bin/"
      - "/Users/jem/Library/pnpm/"
      - "/Users/jem/.local/state/fnm_multishells/22271_1771961984275/bin/"
      - "/Users/jem/.zi/polaris/sbin/"
      - "/Users/jem/.zi/polaris/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/go/bin/"
      - "/Applications/Postgres.app/Contents/Versions/latest/bin/"
      - "/Users/jem/.cargo/bin/"
      - "/Applications/Ghostty.app/Contents/MacOS/"
      - "/Users/jem/.foundry/bin/"
      - "/Users/jem/.cache/lm-studio/bin/"
    searched_directories:
      - "/Users/jem/.antigravity/antigravity/bin/install_name_tool"
      - "/Users/jem/.opencode/bin/install_name_tool"
      - "/Users/jem/.bun/bin/install_name_tool"
      - "/Users/jem/.yarn/bin/install_name_tool"
      - "/Users/jem/.config/yarn/global/node_modules/.bin/install_name_tool"
      - "/Users/jem/.local/state/fnm_multishells/29375_1771963794114/bin/install_name_tool"
      - "/Users/jem/go/bin/install_name_tool"
      - "/Users/jem/code/repos/pixlet/install_name_tool"
      - "/Users/jem/.n/bin/install_name_tool"
      - "/Users/jem/.radicle/bin/install_name_tool"
      - "/Users/jem/.local/bin/install_name_tool"
      - "/Users/jem/Library/pnpm/install_name_tool"
      - "/Users/jem/.local/state/fnm_multishells/22271_1771961984275/bin/install_name_tool"
      - "/Users/jem/.zi/polaris/sbin/install_name_tool"
      - "/Users/jem/.zi/polaris/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/jem/.antigravity/antigravity/bin"
        - "/Users/jem/.opencode/bin"
        - "/Users/jem/.bun/bin"
        - "/Users/jem/.yarn/bin"
        - "/Users/jem/.config/yarn/global/node_modules/.bin"
        - "/Users/jem/.local/state/fnm_multishells/29375_1771963794114/bin"
        - "/Users/jem/go/bin"
        - "/Users/jem/code/repos/pixlet"
        - "/Users/jem/.n/bin"
        - "/Users/jem/.radicle/bin"
        - "/Users/jem/.antigravity/antigravity/bin"
        - "/Users/jem/.opencode/bin"
        - "/Users/jem/.local/bin"
        - "/Users/jem/.bun/bin"
        - "/Users/jem/Library/pnpm"
        - "/Users/jem/.yarn/bin"
        - "/Users/jem/.config/yarn/global/node_modules/.bin"
        - "/Users/jem/.local/state/fnm_multishells/22271_1771961984275/bin"
        - "/Users/jem/.zi/polaris/sbin"
        - "/Users/jem/.zi/polaris/bin"
        - "/Users/jem/go/bin"
        - "/Users/jem/code/repos/pixlet"
        - "/Users/jem/.n/bin"
        - "/Users/jem/.radicle/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/go/bin"
        - "/Applications/Postgres.app/Contents/Versions/latest/bin"
        - "/Users/jem/.cargo/bin"
        - "/Applications/Ghostty.app/Contents/MacOS"
        - "/Users/jem/.foundry/bin"
        - "/Users/jem/.cache/lm-studio/bin"
        - "/Users/jem/.foundry/bin"
        - "/Users/jem/.cache/lm-studio/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
